from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta
from pathlib import Path

from repopulse.storage import Warehouse

DEMO_REPOSITORY = "repopulse/demo-project"


def load_demo_data(db_path: str | Path) -> str:
    """Create a deterministic, interview-friendly dataset without network access."""
    rng = random.Random(42)
    now = datetime.now(UTC).replace(microsecond=0)
    started = now - timedelta(seconds=2)
    authors = ["alex", "bailey", "casey", "devon", "erin", "frank", "gale", "harper"]

    repository = {
        "full_name": DEMO_REPOSITORY,
        "description": "A deterministic demo repository generated by RepoPulse",
        "stargazers_count": 1280,
        "forks_count": 164,
        "subscribers_count": 42,
        "open_issues_count": 18,
        "default_branch": "main",
        "language": "Python",
        "license": {"spdx_id": "MIT"},
        "created_at": _iso(now - timedelta(days=720)),
        "updated_at": _iso(now),
        "pushed_at": _iso(now - timedelta(hours=7)),
    }

    issues = []
    for number in range(1, 81):
        created = now - timedelta(days=rng.randint(3, 360), hours=rng.randint(0, 23))
        is_closed = number % 5 != 0
        close_delay = timedelta(hours=rng.randint(2, 24 * 75))
        closed = min(created + close_delay, now - timedelta(hours=1)) if is_closed else None
        labels = rng.sample(["bug", "enhancement", "docs", "question"], k=1)
        issues.append(
            {
                "number": number,
                "state": "closed" if is_closed else "open",
                "user": {"login": rng.choice(authors)},
                "title": f"Demo issue {number}",
                "labels": [{"name": label} for label in labels],
                "comments": rng.randint(0, 12),
                "locked": False,
                "created_at": _iso(created),
                "updated_at": _iso(closed or created + timedelta(days=2)),
                "closed_at": _iso(closed) if closed else None,
            }
        )

    pull_requests = []
    for number in range(1, 61):
        created = now - timedelta(days=rng.randint(2, 330), hours=rng.randint(0, 23))
        still_open = number % 9 == 0
        draft = number % 17 == 0
        merged = not draft and not still_open and number % 4 != 0
        merged_at = min(created + timedelta(hours=rng.randint(4, 24 * 30)), now) if merged else None
        closed_at = None if still_open else merged_at or min(created + timedelta(days=15), now)
        pull_requests.append(
            {
                "number": number,
                "state": "open" if still_open else "closed",
                "user": {"login": rng.choice(authors)},
                "title": f"Demo pull request {number}",
                "draft": draft,
                "comments": rng.randint(0, 8),
                "review_comments": rng.randint(0, 6),
                "created_at": _iso(created),
                "updated_at": _iso(closed_at or created + timedelta(days=1)),
                "closed_at": _iso(closed_at) if closed_at else None,
                "merged_at": _iso(merged_at) if merged_at else None,
                "merge_commit_sha": f"merge{number:04d}" if merged else None,
            }
        )

    # Weighted authors deliberately create a measurable concentration risk.
    weighted_authors = ["alex"] * 7 + ["bailey"] * 3 + authors[2:]
    commits = []
    for number in range(1, 321):
        committed = now - timedelta(days=rng.randint(0, 360), hours=rng.randint(0, 23))
        author = rng.choice(weighted_authors)
        commits.append(
            {
                "sha": f"demo{number:08d}",
                "author": {"login": author},
                "commit": {
                    "message": f"Demo commit {number}",
                    "author": {"name": author, "date": _iso(committed)},
                    "committer": {"name": author, "date": _iso(committed)},
                },
            }
        )

    releases = []
    for number in range(1, 13):
        published = now - timedelta(days=number * 28)
        releases.append(
            {
                "id": number,
                "tag_name": f"v0.{13 - number}.0",
                "name": f"Demo release {13 - number}",
                "author": {"login": "alex"},
                "draft": False,
                "prerelease": False,
                "created_at": _iso(published - timedelta(days=2)),
                "published_at": _iso(published),
            }
        )

    # Issue comments: closed issues usually get a non-author reply; ~15% of all
    # issues have no reply at all so the no-response ratio is non-trivial.
    maintainers = authors[1:]
    issue_comments = []
    comment_id = 100000
    for issue in issues:
        author = issue["user"]["login"]
        created = _parse_iso(issue["created_at"])
        if rng.random() < 0.15:
            continue  # no response at all
        responder = rng.choice([m for m in maintainers if m != author] or maintainers)
        delay_hours = rng.randint(1, 240)
        issue_comments.append(
            {
                "id": comment_id,
                "issue_number": issue["number"],
                "user": {"login": responder},
                "body": "Demo comment",
                "created_at": _iso(created + timedelta(hours=delay_hours)),
            }
        )
        comment_id += 1

    # PR reviews: most non-draft, non-still-open PRs get a non-author review.
    pr_reviews = []
    review_id = 200000
    for pr in pull_requests:
        author = pr["user"]["login"]
        created = _parse_iso(pr["created_at"])
        if pr["draft"] or rng.random() < 0.2:
            continue
        reviewer = rng.choice([m for m in maintainers if m != author] or maintainers)
        delay_hours = rng.randint(1, 120)
        state = rng.choice(["approved", "commented", "changes_requested"])
        pr_reviews.append(
            {
                "id": review_id,
                "pr_number": pr["number"],
                "user": {"login": reviewer},
                "state": state,
                "body": "Demo review",
                "submitted_at": _iso(created + timedelta(hours=delay_hours)),
            }
        )
        review_id += 1

    with Warehouse(db_path) as warehouse:
        warehouse.initialize()
        warehouse.upsert_repository(repository, now)
        issue_count = warehouse.upsert_issues(DEMO_REPOSITORY, issues)
        pr_count = warehouse.upsert_pull_requests(DEMO_REPOSITORY, pull_requests)
        commit_count = warehouse.upsert_commits(DEMO_REPOSITORY, commits)
        release_count = warehouse.upsert_releases(DEMO_REPOSITORY, releases)
        comment_count = warehouse.upsert_issue_comments(DEMO_REPOSITORY, issue_comments)
        review_count = warehouse.upsert_pr_reviews(DEMO_REPOSITORY, pr_reviews)
        run_id = f"demo-{int(now.timestamp())}"
        warehouse.start_run(run_id, DEMO_REPOSITORY, started)
        warehouse.finish_run(
            run_id,
            finished_at=now,
            status="success",
            counts={
                "issues": issue_count,
                "pull_requests": pr_count,
                "commits": commit_count,
                "releases": release_count,
                "issue_comments": comment_count,
                "pr_reviews": review_count,
            },
        )
    return DEMO_REPOSITORY


def _parse_iso(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _iso(value: datetime) -> str:
    return value.isoformat().replace("+00:00", "Z")
